# Generated by Django 5.1.3 on 2024-12-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_compra_preco"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="compra",
            name="preco",
        ),
        migrations.AddField(
            model_name="itenscompra",
            name="preco",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
